language: python
os: linux
dist: bionic

cache:
  pip: true
  cargo: true

jobs:
  include:
    - name: Python 3.5
      python: "3.5"
    - name: Python 3.6
      python: "3.6"
    - name: Python 3.7
      python: "3.7"
    - name: Python 3.8
      python: "3.8"
      # Run clippy and rustfmt
      env: RUN_LINT=1
    - name: Python 3.9-dev
      python: "3.9-dev"
    - name: Nightly
      python: "3.7"
      env: TRAVIS_RUST_VERSION=nightly FEATURES="nightly"
    - name: PyPy3.5 7.0 # Tested via anaconda PyPy (since travis's PyPy version is too old)
      python: "3.7"
      env: FEATURES="pypy" PATH="$PATH:/opt/anaconda/envs/pypy3/bin"
  allow_failures:
    - name: Nightly
    - python: 3.9-dev

env:
  global:
    - TRAVIS_RUST_VERSION=stable
    - RUST_BACKTRACE=1
    - RUN_LINT=0

before_install:
  - source ./ci/travis/setup.sh
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

install:
  - pip install setuptools-rust pytest pytest-benchmark tox

script:
  - ./ci/travis/test.sh

deploy:
  - provider: script
    script: ./ci/travis/cover.sh
    edge: true
    on:
      branch: master
      repo: PyO3/pyo3
      python: 3.6
      condition: $TRAVIS_EVENT_TYPE != "cron"
  - provider: script
    script: ./ci/travis/guide.sh
    edge: true
    on:
      branch: master
      repo: PyO3/pyo3
      python: 3.6
      condition: $TRAVIS_EVENT_TYPE != "cron"
  - provider: script
    script: ./ci/travis/guide.sh
    edge: true
    on:
      tags: true
      repo: PyO3/pyo3
      python: 3.6

notifications:
  email: false
