[package]
name = "pyo3"
version = "0.5.0"
description = "Bindings to Python interpreter"
authors = ["PyO3 Project and Contributors <https://github.com/PyO3>"]
readme = "README.md"
keywords = ["pyo3", "python", "cpython", "ffi"]
homepage = "https://github.com/pyo3/pyo3"
repository = "https://github.com/pyo3/pyo3"
# Reactivate this once docs.rs is fixed
#documentation = "https://docs.rs/crate/pyo3/"
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
build = "build.rs"

[badges]
travis-ci = { repository = "PyO3/pyo3", branch = "master" }
appveyor = { repository = "fafhrd91/pyo3" }
codecov = { repository = "PyO3/pyo3", branch = "master", service = "github" }

[dependencies]
libc = "0.2.43"
spin = "0.4.9"
num-traits = "0.2.5"
pyo3cls = { path = "pyo3cls", version = "=0.5.0" }
mashup = "0.1.5"

[dev-dependencies]
docmatic = "0.1.2"

[build-dependencies]
regex = "1.0.2"
version_check = "0.1.4"

[features]
default = []

# Use this feature when building python2 binding.
python2 = []

# Use this feature when building python3 binding.
python3 = []

# Use this feature when building an extension module.
# It tells the linker to keep the python symbols unresolved,
# so that the module can also be used with statically linked python interpreters.
extension-module = []

# The stable cpython abi as defined in PEP 384. Currently broken with
# many compilation errors. Pull Requests working towards fixing that
# are welcome.
# abi3 = []

[workspace]
members = [
    "pyo3cls",
    "pyo3-derive-backend",
    "examples/*"
]
