comment: false

coverage:
  status:
    merge:
      project:
        default:
          target: auto
          # Allow a tiny drop of overall project coverage in PR to reduce spurious failures.
          threshold: 0.25%
    project:
      default:
        target: auto
        # Allow a tiny drop of overall project coverage in PR to reduce spurious failures.
        threshold: 0.25%
        branches:
          - main

ignore:
  - tests/
  - pytests/
  - src/test_hygiene/*.rs
