[package]
authors = ["{{authors}}"]
name = "{{project-name}}"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.0.2"
pyo3 = { version = "{{PYO3_VERSION}}", features = ["extension-module"] }

[lib]
name = "word_count"
crate-type = ["cdylib"]
